# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    - package-ecosystem: nuget
      directory: "/"
      schedule:
          interval: daily
      open-pull-requests-limit: 10
registries:
    RMDY-AzureArtifacts:
        type: nuget-feed
        url: 'https://pkgs.dev.azure.com/Growandglow/dotRMDY/_packaging/dotRMDY/nuget/v3/index.json'
        token: 'PAT:${{RMDY_AZURE_ARTIFACTS_TOKEN}}'