trigger: none # Disable CI trigger

schedules:
    - cron: '0 2 * * *' # daily at 2am UTC
      always: true # run even when there are no code changes
      branches:
          include:
              - main
      batch: true
      displayName: Daily

pool:
    vmImage: 'ubuntu-latest' # requires macos or ubuntu (windows is not supported)

steps:
    - task: dependabot@1
      inputs:
          useConfigFile: true
          azureDevOpsAccessToken: '$(System.AccessToken)'
          gitHubConnection: 'GitHub Service Connection'
      env:
          RMDY_AZURE_ARTIFACTS_TOKEN: $(System.AccessToken)